# This workflow will do a clean install of node dependencies, build the source code and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:latest
      env:
        NODE_ENV: development

    steps:
      - uses: actions/checkout@v3

      - name: Terraform Init
        run: make init

